#pragma once

#define PORT 18000
#define BUFFER_SIZE 100

#define PKT_SIZE_DAY 6
#define PKT_SIZE_MONTH 5
#define PKT_SIZE_YEAR 13
#define PKT_SIZE_MINUTES 7
#define PKT_SIZE_MERIDIAN 1
#define PKT_SIZE_HOUR 5
#define PKT_SIZE_SECONDS 7
#define PKT_SIZE_PADDING 4
#define PKT_SIZE_FUEL 32

#define PKT_OFFSET_TO_FUEL PKT_SIZE_DAY + PKT_SIZE_MONTH + PKT_SIZE_YEAR + PKT_SIZE_MINUTES + PKT_SIZE_MERIDIAN + PKT_SIZE_HOUR + PKT_SIZE_SECONDS + PKT_SIZE_PADDING