#pragma once

/// @brief

#define PORT 18000
#define BUFFER_SIZE 32

#define PKT_SIZE_FLAG 1
#define PKT_SIZE_DAY 2
#define PKT_SIZE_MONTH 2
#define PKT_SIZE_YEAR 4
#define PKT_SIZE_MINUTES 2
#define PKT_SIZE_MERIDIAN 1
#define PKT_SIZE_HOUR 2
#define PKT_SIZE_SECONDS 2
#define PKT_SIZE_FUEL 4

#define FLAG_CONTINUE 1
#define FLAG_END 0

#define PKT_OFFSET_TO_FUEL PKT_SIZE_FLAG + PKT_SIZE_DAY + PKT_SIZE_MONTH + PKT_SIZE_YEAR + PKT_SIZE_MINUTES + PKT_SIZE_MERIDIAN + PKT_SIZE_HOUR + PKT_SIZE_SECONDS